import type { Metadata } from "next";
import { Inter, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import HydrationFlagProvider from "@/components/providers/hydration-flag-provider";
import { ReactQueryClientProvider } from "@/components/providers/query-client-provider";
import { ServerTimeProvider } from "@/components/providers/server-time-provider";
import { Toaster } from "@/components/ui/sonner";
import { TooltipProvider } from "@/components/ui/tooltip";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const jetBrainsMono = JetBrains_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        jetBrainsMono.variable,
        "font-sans",
        inter.variable,
      )}
    >
      <body className="min-h-full flex flex-col">
        <ReactQueryClientProvider>
          <NuqsAdapter>
            <ServerTimeProvider serverNow={new Date().toISOString()}>
              <TooltipProvider>
                <HydrationFlagProvider>{children}</HydrationFlagProvider>
              </TooltipProvider>
            </ServerTimeProvider>
          </NuqsAdapter>
        </ReactQueryClientProvider>
        <Toaster />
      </body>
    </html>
  );
}
